export enum Promocode {
  'DARTH_VADER' = 'DARTH_VADER',
  'DEATH_STAR' = 'DEATH_STAR',
  'PADAWAN' = 'PADAWAN',
  'ANAKIN_SKYWALKER' = 'ANAKIN_SKYWALKER',
  'MAY_THE_FORCE_BE_WITH_YOU' = 'MAY_THE_FORCE_BE_WITH_YOU',
}
